.PHONY: clean All

All:
	@echo "----------Building project:[ SMA-EMA - Debug ]----------"
	@cd "SMA-EMA" && "$(MAKE)" -f  "SMA-EMA.mk"
clean:
	@echo "----------Cleaning project:[ SMA-EMA - Debug ]----------"
	@cd "SMA-EMA" && "$(MAKE)" -f  "SMA-EMA.mk" clean
