.PHONY: clean All

All:
	@echo "----------Building project:[ FondamentalAnalyse - Debug ]----------"
	@cd "FondamentalAnalyse" && "$(MAKE)" -f  "FondamentalAnalyse.mk"
clean:
	@echo "----------Cleaning project:[ FondamentalAnalyse - Debug ]----------"
	@cd "FondamentalAnalyse" && "$(MAKE)" -f  "FondamentalAnalyse.mk" clean
